version: '2'

services: 
  fetch_server:
    build: .
    image: shintech/fetch_server:latest
    container_name: fetch_server
    env_file:
      - ./fetch_server.env
    ports:
      - 8001:8001
    restart: always
